name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (to build React GUI)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: ./gui
        run: npm install

      - name: Build frontend
        working-directory: ./gui
        run: npm run build

      - name: Copy frontend build into python package
        run: |
          rm -rf woodwork/gui/dist || true
          mkdir -p woodwork/gui
          cp -r gui/dist woodwork/gui/dist

      - name: Install Python and build tools
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Create virtual environment and install build dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip build twine

      - name: Build package
        run: |
          source .venv/bin/activate
          python -m build

      - name: Publish package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          source .venv/bin/activate
          python -m twine upload dist/*
