name: Run Type Checking

on:
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  type_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ty

      - name: Run type checking with ty
        run: |
          uv run ty check
